/* Myanmar Elite Connect — real site-wide Myanmar cultural UI themes */
(function(){
'use strict';
const THEMES={
'original':{name:'Original',image:'',overlay:'transparent',bg:'#f5f7fb',surface:'#fff',soft:'#f7f9fc',text:'#10233f',muted:'#718097',gold:'#d8b45c'},
'royal-myanmar':{name:'Royal Myanmar',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Shwedagon-Pagode.jpg?width=1800',overlay:'rgba(5,18,38,.72)',bg:'#071a34',surface:'rgba(14,31,53,.94)',soft:'rgba(22,45,72,.92)',text:'#f6f2e7',muted:'#aeb9c8',gold:'#d8b45c'},
'shwedagon-gold':{name:'Shwedagon Gold',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Shwedagon-Pagode.jpg?width=1800',overlay:'rgba(7,20,42,.68)',bg:'#081a31',surface:'rgba(255,255,255,.95)',soft:'rgba(248,244,231,.93)',text:'#10233f',muted:'#66758b',gold:'#dfb95e'},
'kyaiktiyo-heritage':{name:'Kyaiktiyo Heritage',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Kyaiktiyo%20Pagoda.jpg?width=1800',overlay:'rgba(9,21,38,.62)',bg:'#10253a',surface:'rgba(255,253,247,.95)',soft:'rgba(247,240,224,.93)',text:'#182b3c',muted:'#69788a',gold:'#d9b65c'},
'bagan-sunset':{name:'Bagan Heritage',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Bagan%20Temple.jpg?width=1800',overlay:'rgba(48,27,12,.55)',bg:'#3a2515',surface:'rgba(255,250,241,.95)',soft:'rgba(247,235,216,.92)',text:'#2a211a',muted:'#786b5d',gold:'#c99b3b'},
'inle-serenity':{name:'Inle Serenity',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Inle%20Lake%20%28Myanmar%29.jpg?width=1800',overlay:'rgba(5,34,48,.55)',bg:'#0b3344',surface:'rgba(247,252,252,.95)',soft:'rgba(228,241,242,.92)',text:'#102f3b',muted:'#647d84',gold:'#d5b25a'},
'mandalay-palace':{name:'Mandalay Palace',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Mandalay%20Palace%2C%20Myanmar.jpg?width=1800',overlay:'rgba(50,13,23,.60)',bg:'#32121b',surface:'rgba(255,248,245,.95)',soft:'rgba(246,229,224,.92)',text:'#32121b',muted:'#806b6d',gold:'#d8b45c'},
'burmese-lacquer':{name:'Burmese Lacquer',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Bagan%20Temple.jpg?width=1800',overlay:'rgba(8,8,8,.78)',bg:'#0b0b0b',surface:'rgba(25,25,25,.94)',soft:'rgba(40,40,40,.92)',text:'#f5f1e7',muted:'#a9a193',gold:'#d8b45c'},
'thanaka-classic':{name:'Thanaka Classic',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Thanaka.jpg?width=1800',overlay:'rgba(82,61,35,.48)',bg:'#d9c8a8',surface:'rgba(255,252,244,.95)',soft:'rgba(246,239,224,.94)',text:'#3c3024',muted:'#776957',gold:'#b88a2b'},
'myanmar-silk':{name:'Myanmar Silk',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Myanmar%20silk.jpg?width=1800',overlay:'rgba(54,25,38,.42)',bg:'#f6eef0',surface:'rgba(255,250,251,.95)',soft:'rgba(247,235,240,.93)',text:'#3c2730',muted:'#856f77',gold:'#c69a50'},
'jade-myanmar':{name:'Jade Myanmar',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Jade%20market%20Myanmar.jpg?width=1800',overlay:'rgba(8,48,36,.42)',bg:'#e8f2ed',surface:'rgba(251,255,252,.95)',soft:'rgba(231,244,237,.93)',text:'#17362c',muted:'#668176',gold:'#b99743'}
};
function install(){if(document.getElementById('mec-theme-style'))return;const s=document.createElement('style');s.id='mec-theme-style';s.textContent=`
:root{--mec-bg:#f5f7fb;--mec-surface:#fff;--mec-soft:#f7f9fc;--mec-text:#10233f;--mec-muted:#718097;--mec-gold:#d8b45c;--mec-theme-image:none;--mec-overlay:transparent}
body{background:var(--mec-bg)!important;color:var(--mec-text)!important;transition:background .4s,color .3s}
body.mec-theme-image:before{content:"";position:fixed;inset:0;z-index:-20;background:linear-gradient(var(--mec-overlay),var(--mec-overlay)),var(--mec-theme-image) center/cover no-repeat;pointer-events:none}
body.mec-theme-image:after{content:"";position:fixed;inset:0;z-index:-19;background:linear-gradient(180deg,rgba(255,255,255,.03),rgba(255,255,255,.12));pointer-events:none}
body.mec-theme-image .card,body.mec-theme-image .panel,body.mec-theme-image .surface,body.mec-theme-image .listing-card,body.mec-theme-image .info-card{backdrop-filter:blur(9px);-webkit-backdrop-filter:blur(9px)}
body.mec-theme-image .topbar,body.mec-theme-image .mobile-nav{backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px)}
#mecThemeStudio{margin-top:18px}
#mecThemeStudio .mec-theme-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;padding:15px}
#mecThemeStudio .mec-theme-card{position:relative;overflow:hidden;border:1px solid var(--border);border-radius:14px;background:var(--surface);cursor:pointer;transition:.2s ease}
#mecThemeStudio .mec-theme-card:hover{transform:translateY(-2px);border-color:var(--gold);box-shadow:0 12px 30px rgba(0,0,0,.10)}
#mecThemeStudio .mec-theme-card.active{border:2px solid var(--gold)}
#mecThemeStudio .mec-theme-preview{height:105px;background-position:center;background-size:cover;display:flex;align-items:flex-end;padding:10px}
#mecThemeStudio .mec-theme-preview span{padding:5px 7px;border-radius:7px;background:rgba(7,26,52,.78);color:#fff;font-size:8px;font-weight:900}
#mecThemeStudio .mec-theme-name{padding:10px 11px;font-size:10px;font-weight:900;color:var(--text)}
#mecThemeStudio .mec-theme-status{position:absolute;right:8px;top:8px;padding:4px 6px;border-radius:6px;background:var(--gold);color:#071a34;font-size:7px;font-weight:950;display:none}
#mecThemeStudio .active .mec-theme-status{display:block}
#mecThemeStudio .mec-theme-actions{display:flex;justify-content:flex-end;gap:7px;padding:0 15px 15px}
#mecThemeStudio .mec-theme-hint{padding:0 15px 12px;color:var(--muted);font-size:9px;line-height:1.6}
@media(max-width:900px){#mecThemeStudio .mec-theme-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:650px){#mecThemeStudio .mec-theme-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}}
`;document.head.appendChild(s)}
function apply(id){const t=THEMES[id]||THEMES.original;document.documentElement.dataset.mecTheme=THEMES[id]?id:'original';Object.entries({bg:t.bg,surface:t.surface,soft:t.soft,text:t.text,muted:t.muted,gold:t.gold}).forEach(([k,v])=>document.documentElement.style.setProperty('--mec-'+k,v));document.body.classList.toggle('mec-theme-image',!!t.image);document.body.style.setProperty('--mec-theme-image',t.image?`url("${t.image}")`:'none');document.body.style.setProperty('--mec-overlay',t.overlay);localStorage.setItem('mec_ui_theme',THEMES[id]?id:'original');window.dispatchEvent(new CustomEvent('mecThemeChanged',{detail:{id:THEMES[id]?id:'original',name:t.name}}));updateStudio()} 
async function saveRemote(id){const key='sb_publishable_xoh1rjwBlJhR9nB3kQD-KA_QcVY6w2s';const url='https://ikjwisfsdcupibgjiuvp.supabase.co/rest/v1/app_ui_settings';const r=await fetch(url+'?id=eq.1',{method:'PATCH',headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json','Prefer':'return=minimal'},body:JSON.stringify({active_theme:id,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error('Theme save failed ('+r.status+')');}
function createStudio(){if(!location.pathname.toLowerCase().endsWith('/admin.html')||document.getElementById('mecThemeStudio'))return;const panel=document.createElement('section');panel.className='panel';panel.id='mecThemeStudio';panel.innerHTML=`<div class="panel-head"><strong>Myanmar UI / UX Theme Studio</strong><span style="color:var(--muted);font-size:9px">11 themes</span></div><div class="mec-theme-hint">Choose a site-wide background/UI style. Original is the default design. Myanmar cultural themes use heritage imagery while keeping the existing page functions unchanged.</div><div class="mec-theme-grid"></div><div class="mec-theme-actions"><button class="btn" id="mecThemeReset">Original</button><button class="btn primary" id="mecThemeSave">Save Theme</button></div>`;const target=document.querySelector('.content');if(!target)return;target.appendChild(panel);const grid=panel.querySelector('.mec-theme-grid');Object.entries(THEMES).forEach(([id,t])=>{const card=document.createElement('button');card.type='button';card.className='mec-theme-card';card.dataset.theme=id;card.innerHTML=`<div class="mec-theme-preview" style="background-image:${t.image?`linear-gradient(${t.overlay},${t.overlay}),url("${t.image}")`:`linear-gradient(135deg,${t.bg},${t.soft})`}"><span>${t.name}</span></div><div class="mec-theme-name">${t.name}</div><div class="mec-theme-status">ACTIVE</div>`;card.addEventListener('click',()=>apply(id));grid.appendChild(card)});panel.querySelector('#mecThemeReset').addEventListener('click',()=>apply('original'));panel.querySelector('#mecThemeSave').addEventListener('click',async()=>{const id=document.documentElement.dataset.mecTheme||'original';const btn=panel.querySelector('#mecThemeSave');btn.disabled=true;btn.textContent='Saving...';try{await saveRemote(id);btn.textContent='Saved ✓';setTimeout(()=>{btn.disabled=false;btn.textContent='Save Theme'},1200)}catch(e){console.error(e);btn.disabled=false;btn.textContent='Save Theme';alert('Save failed. Make sure app_ui_settings allows admin updates.')}});updateStudio()}
function updateStudio(){const studio=document.getElementById('mecThemeStudio');if(!studio)return;const active=document.documentElement.dataset.mecTheme||localStorage.getItem('mec_ui_theme')||'original';studio.querySelectorAll('.mec-theme-card').forEach(c=>c.classList.toggle('active',c.dataset.theme===active))}
async function load(){install();let active=localStorage.getItem('mec_ui_theme')||'original';try{const r=await fetch('https://ikjwisfsdcupibgjiuvp.supabase.co/rest/v1/app_ui_settings?id=eq.1&select=active_theme',{headers:{apikey:'sb_publishable_xoh1rjwBlJhR9nB3kQD-KA_QcVY6w2s',Authorization:'Bearer sb_publishable_xoh1rjwBlJhR9nB3kQD-KA_QcVY6w2s'}});if(r.ok){const rows=await r.json();if(rows[0]?.active_theme&&THEMES[rows[0].active_theme])active=rows[0].active_theme}}catch(e){console.warn('MEC theme:',e.message)}apply(active);if(location.pathname.toLowerCase().endsWith('/admin.html')){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',createStudio,{once:true});else createStudio()}}
window.MEC_UI_THEMES=THEMES;window.MEC_applyTheme=apply;window.MEC_loadTheme=load;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
