/* Myanmar Elite Connect — site-wide Myanmar cultural UI/UX theme system */
(function(){
'use strict';
const THEMES={
original:{name:'Original',desc:'The original Myanmar Elite Connect design.',image:'',overlay:'',bg:'#f5f7fb',surface:'#ffffff',soft:'#f7f9fc',text:'#10233f',muted:'#718097',border:'rgba(16,35,63,.10)',gold:'#d8b45c'},
shwedagon:{name:'Shwedagon Gold',desc:'Shwedagon Pagoda with refined gold and navy.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Shwedagon-Pagode.jpg?width=1800',overlay:'rgba(7,20,42,.62)',bg:'#081a31',surface:'rgba(255,255,255,.94)',soft:'rgba(248,244,231,.92)',text:'#10233f',muted:'#66758b',border:'rgba(216,180,92,.18)',gold:'#dfb95e'},
kyaiktiyo:{name:'Kyaiktiyo Heritage',desc:'Kyaiktiyo Pagoda inspired heritage atmosphere.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Kyaiktiyo%20Pagoda.jpg?width=1800',overlay:'rgba(9,21,38,.58)',bg:'#10253a',surface:'rgba(255,253,247,.94)',soft:'rgba(247,240,224,.92)',text:'#182b3c',muted:'#69788a',border:'rgba(201,166,84,.18)',gold:'#d9b65c'},
bagan:{name:'Bagan Heritage',desc:'Warm Bagan temples and classic Myanmar earth tones.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Bagan%20Temple.jpg?width=1800',overlay:'rgba(48,27,12,.52)',bg:'#3a2515',surface:'rgba(255,250,241,.94)',soft:'rgba(247,235,216,.92)',text:'#2a211a',muted:'#786b5d',border:'rgba(167,117,54,.18)',gold:'#c99b3b'},
inle:{name:'Inle Serenity',desc:'Calm Inle Lake inspired by water, sky and gold.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Inle%20Lake%20%28Myanmar%29.jpg?width=1800',overlay:'rgba(5,34,48,.54)',bg:'#0b3344',surface:'rgba(247,252,252,.94)',soft:'rgba(228,241,242,.92)',text:'#102f3b',muted:'#647d84',border:'rgba(64,132,142,.18)',gold:'#d5b25a'},
mandalay:{name:'Mandalay Palace',desc:'Mandalay royal heritage with elegant burgundy.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Mandalay%20Palace%2C%20Myanmar.jpg?width=1800',overlay:'rgba(50,13,23,.58)',bg:'#32121b',surface:'rgba(255,248,245,.94)',soft:'rgba(246,229,224,.92)',text:'#32121b',muted:'#806b6d',border:'rgba(155,73,77,.18)',gold:'#d8b45c'},
lacquer:{name:'Burmese Lacquer',desc:'Dark lacquerware inspired luxury with gold.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Burmese%20lacquerware.jpg?width=1800',overlay:'rgba(8,8,8,.72)',bg:'#0b0b0b',surface:'rgba(25,25,25,.94)',soft:'rgba(40,40,40,.92)',text:'#f5f1e7',muted:'#a9a193',border:'rgba(216,180,92,.18)',gold:'#d8b45c'},
thanaka:{name:'Thanaka Classic',desc:'Soft natural tones inspired by Myanmar thanaka.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Thanaka.jpg?width=1800',overlay:'rgba(82,61,35,.44)',bg:'#d9c8a8',surface:'rgba(255,252,244,.94)',soft:'rgba(246,239,224,.94)',text:'#3c3024',muted:'#776957',border:'rgba(111,90,50,.16)',gold:'#b88a2b'},
silk:{name:'Myanmar Silk',desc:'Elegant silk-inspired burgundy and ivory.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Myanmar%20silk.jpg?width=1800',overlay:'rgba(54,25,38,.38)',bg:'#f6eef0',surface:'rgba(255,250,251,.94)',soft:'rgba(247,235,240,.93)',text:'#3c2730',muted:'#856f77',border:'rgba(126,72,95,.15)',gold:'#c69a50'},
jade:{name:'Jade Myanmar',desc:'Myanmar jade-inspired green with understated gold.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Jade%20market%20Myanmar.jpg?width=1800',overlay:'rgba(8,48,36,.38)',bg:'#e8f2ed',surface:'rgba(251,255,252,.94)',soft:'rgba(231,244,237,.93)',text:'#17362c',muted:'#668176',border:'rgba(35,104,74,.15)',gold:'#b99743'},
royal:{name:'Royal Myanmar',desc:'Deep navy, ivory and gold inspired by royal Myanmar.',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Mandalay%20Palace%2C%20Myanmar.jpg?width=1800',overlay:'rgba(5,18,38,.70)',bg:'#071a34',surface:'rgba(14,31,53,.94)',soft:'rgba(22,45,72,.92)',text:'#f6f2e7',muted:'#aeb9c8',border:'rgba(216,180,92,.18)',gold:'#d8b45c'}
};
const KEY='mec_ui_theme';
const SB_URL='https://ikjwisfsdcupibgjiuvp.supabase.co';
const SB_KEY='sb_publishable_xoh1rjwBlJhR9nB3kQD-KA_QcVY6w2s';
function install(){if(document.getElementById('mec-theme-style'))return;const s=document.createElement('style');s.id='mec-theme-style';s.textContent=`
body[data-mec-theme]{background-color:var(--mec-bg)!important;color:var(--mec-text)!important;transition:background .35s ease,color .25s ease}
body.mec-has-theme-image[data-mec-theme]{background-image:linear-gradient(var(--mec-overlay),var(--mec-overlay)),var(--mec-theme-image)!important;background-position:center top!important;background-size:cover!important;background-attachment:fixed!important;background-repeat:no-repeat!important}
body[data-mec-theme] .card,body[data-mec-theme] .panel,body[data-mec-theme] .sidebar,body[data-mec-theme] .stat,body[data-mec-theme] .info-card,body[data-mec-theme] .listing-card,body[data-mec-theme] .post-card,body[data-mec-theme] .modal-box,body[data-mec-theme] .profile-card,body[data-mec-theme] .form-card,body[data-mec-theme] .surface{background:var(--mec-surface)!important;border-color:var(--mec-border)!important;color:var(--mec-text)!important}
body[data-mec-theme] input,body[data-mec-theme] select,body[data-mec-theme] textarea,body[data-mec-theme] .search,body[data-mec-theme] .filter{background:var(--mec-soft)!important;color:var(--mec-text)!important;border-color:var(--mec-border)!important}
body[data-mec-theme] .topbar,body[data-mec-theme] .mobile-nav,body[data-mec-theme] #mec-global-nav{background:var(--mec-surface)!important;border-color:var(--mec-border)!important}
body[data-mec-theme] .nav a:hover,body[data-mec-theme] .nav a.active,body[data-mec-theme] .side-btn:hover,body[data-mec-theme] .side-btn.active{background:var(--mec-soft)!important;color:var(--mec-text)!important}
body[data-mec-theme] .eyebrow,body[data-mec-theme] .section-note,body[data-mec-theme] .preview-category,body[data-mec-theme] .mobile-nav a.active,body[data-mec-theme] .mec-nav-label{color:var(--mec-gold)!important}
body[data-mec-theme] .publish-button,body[data-mec-theme] .btn.primary{background:var(--mec-gold)!important;border-color:var(--mec-gold)!important}
#mec-theme-view .mec-theme-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;padding:15px}
#mec-theme-view .mec-theme-option{position:relative;overflow:hidden;padding:0;border:1px solid var(--border);border-radius:14px;background:var(--surface);color:var(--text);cursor:pointer;text-align:left;transition:.2s}
#mec-theme-view .mec-theme-option:hover{transform:translateY(-2px);border-color:var(--gold)}
#mec-theme-view .mec-theme-option.active{border:2px solid var(--gold)}
#mec-theme-view .mec-theme-swatch{height:105px;background-position:center;background-size:cover}
#mec-theme-view .mec-theme-name{padding:9px 10px 2px;font-size:10px;font-weight:950}
#mec-theme-view .mec-theme-desc{padding:0 10px 10px;color:var(--muted);font-size:8px;line-height:1.5}
#mec-theme-view .mec-theme-active{position:absolute;right:7px;top:7px;display:none;padding:4px 6px;border-radius:6px;background:var(--gold);color:#071a34;font-size:7px;font-weight:950}
#mec-theme-view .active .mec-theme-active{display:block}
#mec-theme-view .mec-theme-footer{display:flex;justify-content:flex-end;gap:7px;padding:0 15px 15px;align-items:center}
#mec-theme-view .mec-theme-status{margin-right:auto;color:var(--muted);font-size:9px}
@media(max-width:900px){#mec-theme-view .mec-theme-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:600px){#mec-theme-view .mec-theme-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function apply(id,save=true){const t=THEMES[id]||THEMES.original,r=document.documentElement;Object.entries({bg:t.bg,surface:t.surface,soft:t.soft,text:t.text,muted:t.muted,border:t.border,gold:t.gold}).forEach(([k,v])=>r.style.setProperty('--mec-'+k,v));r.style.setProperty('--mec-overlay',t.overlay||'transparent');r.style.setProperty('--mec-theme-image',t.image?`url("${t.image}")`:'none');r.dataset.mecTheme=id;if(document.body){document.body.dataset.mecTheme=id;document.body.classList.toggle('mec-has-theme-image',!!t.image)}if(save)localStorage.setItem(KEY,id);updateView()}
async function load(){install();let id=localStorage.getItem(KEY)||'original';try{if(window.supabaseClient){const q=await window.supabaseClient.from('app_ui_settings').select('active_theme').eq('id',1).maybeSingle();if(!q.error&&THEMES[q.data?.active_theme])id=q.data.active_theme}}catch(e){}apply(id,false)}
function updateView(){const v=document.getElementById('mec-theme-view');if(!v)return;const a=document.documentElement.dataset.mecTheme||'original';v.querySelectorAll('.mec-theme-option').forEach(x=>x.classList.toggle('active',x.dataset.theme===a))}
function openView(){const v=document.getElementById('mec-theme-view');if(!v)return;document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));v.classList.add('active');document.querySelectorAll('.side-btn').forEach(x=>x.classList.remove('active'));document.getElementById('mec-theme-menu')?.classList.add('active');window.scrollTo(0,0)}
async function saveTheme(){const btn=document.getElementById('mec-theme-save'),st=document.getElementById('mec-theme-status'),id=document.documentElement.dataset.mecTheme||'original';btn.disabled=true;btn.textContent='Saving…';st.textContent='Saving theme for all pages…';try{let ok=false;if(window.supabaseClient){try{const r=await window.supabaseClient.rpc('admin_set_ui_theme',{p_theme:id});if(!r.error)ok=true}catch(e){}if(!ok){const r=await window.supabaseClient.from('app_ui_settings').upsert({id:1,active_theme:id,updated_at:new Date().toISOString()},{onConflict:'id'});if(r.error)throw r.error;ok=true}}if(!ok){const r=await fetch(SB_URL+'/rest/v1/app_ui_settings?id=eq.1',{method:'PATCH',headers:{apikey:SB_KEY,Authorization:'Bearer '+SB_KEY,'Content-Type':'application/json','Prefer':'return=minimal'},body:JSON.stringify({active_theme:id,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error('HTTP '+r.status)}localStorage.setItem(KEY,id);st.textContent='✓ Saved. This theme is now the site-wide theme.'}catch(e){console.error(e);st.textContent='Save failed: '+(e?.message||'Database permission denied')}finally{btn.disabled=false;btn.textContent='Save Theme'}}
function admin(){if(!/admin\.html$/i.test(location.pathname)||document.getElementById('mec-theme-view'))return;const side=document.querySelector('.sidebar'),content=document.querySelector('.content');if(!side||!content)return;const m=document.createElement('button');m.id='mec-theme-menu';m.type='button';m.className='side-btn';m.innerHTML='✦ UI / UX';m.onclick=openView;side.appendChild(m);const v=document.createElement('section');v.id='mec-theme-view';v.className='view';v.innerHTML=`<div class="page-head"><div><div class="eyebrow">DESIGN CONTROL</div><h1>UI / UX Themes</h1><p class="subtitle">Change only the visual background and UI/UX style across the website.</p></div></div><div class="panel"><div class="panel-head"><strong>Myanmar Culture UI / UX</strong><span style="color:var(--muted);font-size:9px">11 themes</span></div><div class="mec-theme-grid"></div><div class="mec-theme-footer"><div id="mec-theme-status" class="mec-theme-status">Choose a theme and save it.</div><button type="button" class="btn" id="mec-theme-original">Original</button><button type="button" class="btn primary" id="mec-theme-save">Save Theme</button></div></div>`;content.appendChild(v);const grid=v.querySelector('.mec-theme-grid');Object.entries(THEMES).forEach(([id,t])=>{const o=document.createElement('button');o.type='button';o.className='mec-theme-option';o.dataset.theme=id;const bg=t.image?`linear-gradient(${t.overlay},${t.overlay}),url("${t.image}")`:`linear-gradient(135deg,${t.bg},${t.soft})`;o.innerHTML=`<div class="mec-theme-swatch" style="background-image:${bg}"></div><span class="mec-theme-active">ACTIVE</span><div class="mec-theme-name">${t.name}</div><div class="mec-theme-desc">${t.desc}</div>`;o.onclick=()=>{apply(id,true);v.querySelector('#mec-theme-status').textContent=t.name+' selected — press Save Theme.'};grid.appendChild(o)});v.querySelector('#mec-theme-original').onclick=()=>{apply('original',true);v.querySelector('#mec-theme-status').textContent='Original selected — press Save Theme.'};v.querySelector('#mec-theme-save').onclick=saveTheme;updateView()}
function boot(){load();if(/admin\.html$/i.test(location.pathname)){const f=()=>admin();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(f,400),{once:true});else setTimeout(f,400)}}
window.MEC_UI_THEMES=THEMES;window.MEC_applyTheme=apply;boot();
})();
